[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
merkle_distributor = "AtXLVASdFhmdq2KZxzhVFonmNXL76dTTsEABXySEHgLh"

[programs.localnet]
merkle_distributor = "AtXLVASdFhmdq2KZxzhVFonmNXL76dTTsEABXySEHgLh"

[programs.mainnet]
merkle_distributor = "AtXLVASdFhmdq2KZxzhVFonmNXL76dTTsEABXySEHgLh"

[programs.testnet]
merkle_distributor = "AtXLVASdFhmdq2KZxzhVFonmNXL76dTTsEABXySEHgLh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/merkle-distributor"]

[scripts]
test = "yarn mocha"
