[package]
name = "merkle-distributor"
version = "0.0.2"
description = "A Solana program for distributing tokens according to a Merkle root."
edition = "2021"
license = "GPL-3.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "merkle_distributor"
path = "src/lib.rs"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = ["devnet"]
devnet = []
mainnet-beta = []
anchor-debug = []
custom-heap = []
custom-panic = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { workspace = true }
anchor-spl = { workspace = true }
bytemuck = "1.14.0"
jito-merkle-verify = { path = "../../verify" }
solana-program = { workspace = true }
solana-security-txt = "1.1.1"
